### ISSUE TITLE
classifierClient.py", line 199   IndexError: list assignment index out of range /data/aipost/demo_eeg.txt

### ISSUE THREAD

**Issue by Aazyla** [tarotez/sleepstages#2]
Is a an input file problem or script? (running on Linux Ubuntu)

$ python app_offline.py

n ParameterSetup, paramFilePath = ../data/pickled/params.json
in ParameterSetup, paramFilePath = ../data/pickled/params.json
for EEG, reading file ../data/aipost/demo_eeg.csv
---------------------
Started to read ../data/aipost/demo_eeg.csv. It may take a few minutes before starting to classify. Please wait.
---------------------
list assignment index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ /Soft/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ /Soft/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ /Soft/sleepstages/code/app.py", line 125, in start_reader
    raise e
  File "/home/ /Soft/sleepstages/code/app.py", line 118, in start_reader
    self.server = EEGFileReaderServer(self.client, eegFilePath)
  File "/home/ /Soft/sleepstages/code/eegFileReaderServer.py", line 50, in __init__
    self.serve()
  File "/home/ /Soft/sleepstages/code/eegFileReaderServer.py", line 105, in serve
    self.client.process(dataToClient)
  File "/home/ /Soft/sleepstages/code/classifierClient.py", line 199, in process
    timeStampSegment[sampleCnt] = input_elems[0]
IndexError: list assignment index out of range

**Comment by tarotez** [comment]
The file demo_eeg.csv is now changed to demo_eeg.txt. Hopefully it works by updating?
